### ISSUE TITLE
Store check fails due to manager OCI filesystem cannot be accessed

### ISSUE THREAD

**Issue by blaqkube** [blaqkube/mysql-operator#139]
## Describe the bug

When creating a store on AWS or GKE with the right credentials, it fails with the following status in the `kubectl get store -o yaml`

```
  message: 'Cannot initialize local file, error: open .mysql-operator.out: permission
    denied'
  ready: "False"
  reason: CheckFailed
```

## To Reproduce

1. Rely on the `quay.io/blaqkube/mysql-controller:0.4.0` controller
2. Create the right credentials with AWS so that the store can actually be accessed
3. Create a store on s3

```yaml
apiVersion: mysql.blaqkube.io/v1alpha1
kind: Store
metadata:
  name: red-store
spec:
  backend: s3
  bucket: logs.blaqkube.io
  prefix: /backups/red
  envs:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: red-store
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: red-store
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_REGION
    valueFrom:
      secretKeyRef:
        name: red-store
        key: AWS_REGION
```

4. Check the store status with the command below

```shell
kubectl get store logs.blaqkube.io -o yaml
```

## Expected behavior
The check for the store should succeed

## Infrastructure (please complete the following information):
 - Operator: v0.4.0
 - OLM: any
 - Kubernetes: any
 
## Additional context
N/A
